//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangCap_NhanVien
    {
        public string MA_NV { get; set; }
        public string MA_BC { get; set; }
        public string NOI_CAP { get; set; }
        public System.DateTime NGAY_CAP { get; set; }
    }
}
