//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangChamCong
    {
        public string MA_CC { get; set; }
        public int Thang { get; set; }
        public int Nam { get; set; }
        public Nullable<bool> Tinh_Trang { get; set; }
    }
}
