//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangLuong
    {
        public string MA_NV { get; set; }
        public string MA_LUONG { get; set; }
        public string MA_CC { get; set; }
        public Nullable<double> Thue_TNCN { get; set; }
        public Nullable<double> Tam_Ung { get; set; }
        public Nullable<double> Thuc_Lanh { get; set; }
    }
}
