//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDongLaoDong
    {
        public string MA_HD { get; set; }
        public string MA_NV { get; set; }
        public string LOAI_HD { get; set; }
        public Nullable<System.DateTime> NGAY_BD { get; set; }
        public Nullable<System.DateTime> NGAY_KT { get; set; }
        public System.DateTime NGAY_KY { get; set; }
        public int LAN_KY { get; set; }
        public string NOI_DUNG { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
