//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class KetQuaDanhGia
    {
        public string MA_DG { get; set; }
        public string MA_UV { get; set; }
        public string KET_QUA { get; set; }
        public string GHI_CHU { get; set; }
    }
}
