//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLyNhanSuEntities2 : DbContext
    {
        public QuanLyNhanSuEntities2()
            : base("name=QuanLyNhanSuEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BangCap> BangCaps { get; set; }
        public virtual DbSet<BangCap_NhanVien> BangCap_NhanVien { get; set; }
        public virtual DbSet<BangChamCong> BangChamCongs { get; set; }
        public virtual DbSet<BangLuong> BangLuongs { get; set; }
        public virtual DbSet<BaoHiem> BaoHiems { get; set; }
        public virtual DbSet<ChiTietChamCong> ChiTietChamCongs { get; set; }
        public virtual DbSet<ChucVu> ChucVus { get; set; }
        public virtual DbSet<DanhGia> DanhGias { get; set; }
        public virtual DbSet<HopDongLaoDong> HopDongLaoDongs { get; set; }
        public virtual DbSet<KetQuaDanhGia> KetQuaDanhGias { get; set; }
        public virtual DbSet<NgoaiNgu> NgoaiNgus { get; set; }
        public virtual DbSet<NgoaiNgu_NhanVien> NgoaiNgu_NhanVien { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PhongBan> PhongBans { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<ThongTinLuong> ThongTinLuongs { get; set; }
        public virtual DbSet<UngVien> UngViens { get; set; }
    
        [DbFunction("QuanLyNhanSuEntities2", "LapBangLuong3")]
        public virtual IQueryable<LapBangLuong3_Result> LapBangLuong3(Nullable<int> thang, Nullable<int> nam)
        {
            var thangParameter = thang.HasValue ?
                new ObjectParameter("Thang", thang) :
                new ObjectParameter("Thang", typeof(int));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("Nam", nam) :
                new ObjectParameter("Nam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<LapBangLuong3_Result>("[QuanLyNhanSuEntities2].[LapBangLuong3](@Thang, @Nam)", thangParameter, namParameter);
        }
    
        [DbFunction("QuanLyNhanSuEntities2", "THONG_KE_NV_CV")]
        public virtual IQueryable<THONG_KE_NV_CV_Result> THONG_KE_NV_CV()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<THONG_KE_NV_CV_Result>("[QuanLyNhanSuEntities2].[THONG_KE_NV_CV]()");
        }
    
        [DbFunction("QuanLyNhanSuEntities2", "THONG_KE_NV_PB2")]
        public virtual IQueryable<THONG_KE_NV_PB2_Result> THONG_KE_NV_PB2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<THONG_KE_NV_PB2_Result>("[QuanLyNhanSuEntities2].[THONG_KE_NV_PB2]()");
        }
    
        [DbFunction("QuanLyNhanSuEntities2", "getTL")]
        public virtual IQueryable<getTL_Result> getTL(Nullable<int> thang, Nullable<int> nam)
        {
            var thangParameter = thang.HasValue ?
                new ObjectParameter("Thang", thang) :
                new ObjectParameter("Thang", typeof(int));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("Nam", nam) :
                new ObjectParameter("Nam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<getTL_Result>("[QuanLyNhanSuEntities2].[getTL](@Thang, @Nam)", thangParameter, namParameter);
        }
    
        [DbFunction("QuanLyNhanSuEntities2", "Thong_Ke_Luong1")]
        public virtual IQueryable<Thong_Ke_Luong1_Result> Thong_Ke_Luong1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Thong_Ke_Luong1_Result>("[QuanLyNhanSuEntities2].[Thong_Ke_Luong1]()");
        }
    
        [DbFunction("QuanLyNhanSuEntities2", "Thong_Ke_Luong2")]
        public virtual IQueryable<Thong_Ke_Luong2_Result> Thong_Ke_Luong2(Nullable<int> thangS, Nullable<int> thangE, Nullable<int> namS, Nullable<int> namE)
        {
            var thangSParameter = thangS.HasValue ?
                new ObjectParameter("ThangS", thangS) :
                new ObjectParameter("ThangS", typeof(int));
    
            var thangEParameter = thangE.HasValue ?
                new ObjectParameter("ThangE", thangE) :
                new ObjectParameter("ThangE", typeof(int));
    
            var namSParameter = namS.HasValue ?
                new ObjectParameter("NamS", namS) :
                new ObjectParameter("NamS", typeof(int));
    
            var namEParameter = namE.HasValue ?
                new ObjectParameter("NamE", namE) :
                new ObjectParameter("NamE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Thong_Ke_Luong2_Result>("[QuanLyNhanSuEntities2].[Thong_Ke_Luong2](@ThangS, @ThangE, @NamS, @NamE)", thangSParameter, thangEParameter, namSParameter, namEParameter);
        }
    
        [DbFunction("QuanLyNhanSuEntities2", "Thong_Ke_Luong3")]
        public virtual IQueryable<Thong_Ke_Luong3_Result> Thong_Ke_Luong3(Nullable<int> thangS, Nullable<int> thangE, Nullable<int> namS, Nullable<int> namE)
        {
            var thangSParameter = thangS.HasValue ?
                new ObjectParameter("ThangS", thangS) :
                new ObjectParameter("ThangS", typeof(int));
    
            var thangEParameter = thangE.HasValue ?
                new ObjectParameter("ThangE", thangE) :
                new ObjectParameter("ThangE", typeof(int));
    
            var namSParameter = namS.HasValue ?
                new ObjectParameter("NamS", namS) :
                new ObjectParameter("NamS", typeof(int));
    
            var namEParameter = namE.HasValue ?
                new ObjectParameter("NamE", namE) :
                new ObjectParameter("NamE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Thong_Ke_Luong3_Result>("[QuanLyNhanSuEntities2].[Thong_Ke_Luong3](@ThangS, @ThangE, @NamS, @NamE)", thangSParameter, thangEParameter, namSParameter, namEParameter);
        }
    
        [DbFunction("QuanLyNhanSuEntities2", "Thong_Ke_Luong4")]
        public virtual IQueryable<Thong_Ke_Luong4_Result> Thong_Ke_Luong4(Nullable<int> thangS, Nullable<int> thangE, Nullable<int> nam)
        {
            var thangSParameter = thangS.HasValue ?
                new ObjectParameter("ThangS", thangS) :
                new ObjectParameter("ThangS", typeof(int));
    
            var thangEParameter = thangE.HasValue ?
                new ObjectParameter("ThangE", thangE) :
                new ObjectParameter("ThangE", typeof(int));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("Nam", nam) :
                new ObjectParameter("Nam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Thong_Ke_Luong4_Result>("[QuanLyNhanSuEntities2].[Thong_Ke_Luong4](@ThangS, @ThangE, @Nam)", thangSParameter, thangEParameter, namParameter);
        }
    }
}
