//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public string Ten_TK { get; set; }
        public string Mat_Khau { get; set; }
        public int Loai_Tk { get; set; }
        public string MA_NV { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
